# Generated by Django 3.0 on 2023-12-26 15:59

from django.db import migrations


def forwards_func(apps, schema_editor):
    OldLetting = apps.get_model("oc_lettings_site", "Letting")
    NewLetting = apps.get_model("lettings", "Letting")

    new_lettings = NewLetting.objects.all()
    if new_lettings:
        for letting in new_lettings:
            letting.delete()

    NewLetting.objects.bulk_create(
        NewLetting(
            title=old_letting.title,
            address_id=old_letting.address.id,
        ) for old_letting in OldLetting.objects.all()
    )


def reverse_func(apps, schema_editor):
    OldLetting = apps.get_model("oc_lettings_site", "Letting")
    NewLetting = apps.get_model("lettings", "Letting")

    old_lettings = OldLetting.objects.all()
    if old_lettings:
        for Letting in old_lettings:
            Letting.delete()

    OldLetting.objects.bulk_create(
        OldLetting(
            title=new_letting.title,
            address_id=new_letting.address.id,
        ) for new_letting in NewLetting.objects.all()
    )


class Migration(migrations.Migration):
    """launch the migration operations"""

    dependencies = [
        ('lettings', '0002_auto_20231226_1213'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
