# Generated by Django 3.0 on 2023-12-29 10:43

from django.db import migrations


class Migration(migrations.Migration):
    """
    Correction du pluriel affiché de la table address
    """

    dependencies = [
        ('lettings', '0003_auto_20231226_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
    ]
