# CircleCI configuration file
version: 2.1

orbs:
  python: circleci/python@2.1.1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy

jobs:
  build:
    docker:
      - image: cimg/python:3.12.1
    executor: python/default
    steps:
        - checkout
        - python/install-packages:
            pkg-manager: pip
        - run:
            name: Execute tests suite
            command: |
              pip --version
              pip install -r requirements.txt
              pytest
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
        name: "Deploy"
        command: curl -X GET https://api.render.com/deploy/srv-cmfaeoen7f5s7384hntg?key=9ibAi315EPs