# CircleCI configuration file
version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build:
    docker:
     - image: cimg/base:2022.05
    executor: python/default # use the default executor defined within the orb
    steps:
        - checkout # checkout source code
        - python/install-packages:
            pkg-manager: pip
        - run:
            name: Execute tests suite
            command: |

              pip install -r requirements.txt
              pytest