# CircleCI configuration file
version: 2.1

orbs:
  python: circleci/python@2.1.1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - tests
      - build:
          requires:
            - tests
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
jobs:
  tests:
    docker:
      - image: cimg/python:3.12.1
    executor: python/default
    steps:
        - checkout
        - python/install-packages:
            pkg-manager: pip
        - run:
            name: Execute tests suite
            command: |
              pip --version
              pip install -r requirements.txt
              pytest
  build:
    docker:
      - image: cimg/python:3.8
    steps:
        - checkout
        - setup_remote_docker:
            docker_layer_caching: true
        - run:
            name: "Build Docker Image"
            command: |
              docker build -t oc-letting .
              docker save -o oc-letting.tar oc-letting
        - persist_to_workspace:
            root: .
            paths:
              - oc-letting.tar

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
        - checkout
        - setup_remote_docker
        - attach_workspace:
            at: .
        - run:
            name: "Load docker image"
            command: docker load -i oc-letting.tar
        - run:
            name: "Deploy"
            command: curl -X GET https://api.render.com/deploy/srv-cmfaeoen7f5s7384hntg?key=9ibAi315EPs