# CircleCI configuration file
version: 2.1

orbs:
  python: circleci/python@2.1.1

workflows:
  build_and_deploy:
    jobs:
      - tests
      - build:
          requires:
            - tests
          filters:
            branches:
              only:
                - dev
                - master
                # TODO comment
                - circleCiConfig/automate-push-docker-hub
      - publish-latest:
          requires:
            - build
          # TODO uncomment
          # filters:
          #   branches:
          #     only:
          #       - dev
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
jobs:
  tests:
    docker:
      - image: cimg/python:3.12.1
    executor: python/default
    steps:
        - checkout
        - python/install-packages:
            pkg-manager: pip
        - run:
            name: Execute tests suite
            command: |
              pip --version
              pip install -r requirements.txt
              pytest --cov=. --cov-fail-under=80
  build:
    docker:
      - image: cimg/python:3.8
    steps:
        - checkout
        - setup_remote_docker:
            docker_layer_caching: true
        - run:
            name: "Build Docker Image"
            command: |
              docker build -t daguinci/oc-letting .
              docker save -o oc-letting.tar daguinci/oc-letting
        - persist_to_workspace:
            root: .
            paths:
              - oc-letting.tar
  publish-latest:
    docker:
      - image: cimg/base:stable
    steps:
        - checkout
        - setup_remote_docker:
            docker_layer_caching: true
        # - attach_workspace:
        #     at: .
        - run:
            name: "Connect to docker hub"
            command: |
              echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
        - run:
            name: "Publish latest image in docker hub"
            command: docker push daguinci/oc-letting
  #     - setup_remote_docker:
  #           docker_layer_caching: true
  #     - attach_workspace:
  #         at: .
  #     - run:
  #         name: "Load docker image"
  #         command: docker load -i oc-letting.tar

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
        - checkout
        - setup_remote_docker
        - attach_workspace:
            at: .
        - run:
            name: "Load docker image"
            command: docker load -i oc-letting.tar
        - run:
            name: "Deploy"
            command: curl -X GET https://api.render.com/deploy/srv-cmfaeoen7f5s7384hntg?key=9ibAi315EPs