# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
     - image: cimg/base:2022.05
    steps:
        - checkout
        - run:
            name: Execute tests suite
            command: |
              pytest